name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Run tests
      run: go test -v ./...

    - name: Build for multiple platforms
      run: |
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.version=${{ github.ref_name }}" -o bin/radb-client-linux-amd64 ./cmd/radb-client

        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -ldflags "-s -w -X main.version=${{ github.ref_name }}" -o bin/radb-client-linux-arm64 ./cmd/radb-client

        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w -X main.version=${{ github.ref_name }}" -o bin/radb-client-darwin-amd64 ./cmd/radb-client

        # macOS arm64
        GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w -X main.version=${{ github.ref_name }}" -o bin/radb-client-darwin-arm64 ./cmd/radb-client

        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X main.version=${{ github.ref_name }}" -o bin/radb-client-windows-amd64.exe ./cmd/radb-client

    - name: Generate checksums
      run: |
        cd bin
        sha256sum * > checksums.txt
        cat checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/radb-client-linux-amd64
          bin/radb-client-linux-arm64
          bin/radb-client-darwin-amd64
          bin/radb-client-darwin-arm64
          bin/radb-client-windows-amd64.exe
          bin/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
